id: AE7EC8374
title: THE DHARAṆĪMANTRAPADA OF THE FOUR GREAT KINGS
type: translation
source_metadata:
  languages:
  - bo
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:23:09.108427
  last_modified_at: 2022-03-01 21:23:09.108431
