id: AE7EC8374
title: DHARAṆĪPADA OF ŚAKRA DEVĀNĀMINDRA
type: translation
source_metadata:
  languages:
  - bo
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:23:09.103600
  last_modified_at: 2022-03-01 21:23:09.103605
