id: AE7EC8374
title: Colophon
type: translation
source_metadata:
  languages:
  - bo
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:23:09.101758
  last_modified_at: 2022-03-01 21:23:09.101765
